import Head from 'next/head'
import Header from '../components/Header';
import Parallax from '../components/Parallax';

export default function Home() {
  return (
    <>
      <Head>
        <title>Kalachakra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Parallax />
    </>
  )
}